#!/usr/bin/env node
// Bootstrap this repo into ~/.claude and ~/.local/bin by symlinking.
// Called by bootstrap.sh after it has verified Node is available.

'use strict';

const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { spawnSync } = require('node:child_process');

const REPO        = path.dirname(fs.realpathSync(__filename));
const HOME        = os.homedir();
const CLAUDE      = path.join(HOME, '.claude');
const SKILLS_BASE = path.join(HOME, '.agents', 'skills');
const LOCAL_BIN   = path.join(HOME, '.local', 'bin');

for (const d of [
  CLAUDE,
  path.join(CLAUDE, 'plugins'),
  path.join(CLAUDE, 'skills'),
  path.join(CLAUDE, 'rules'),
  SKILLS_BASE,
  LOCAL_BIN,
]) {
  fs.mkdirSync(d, { recursive: true });
}

function link(src, dst) {
  let existing = null;
  try { existing = fs.lstatSync(dst); } catch { /* ENOENT */ }

  if (existing) {
    if (existing.isSymbolicLink()) {
      const cur = fs.readlinkSync(dst);
      if (cur === src) { console.log(`    ok   ${dst}`); return; }
      console.log(`    relink ${dst} (was -> ${cur})`);
      fs.unlinkSync(dst);
    } else {
      const backup = `${dst}.backup.${Date.now()}`;
      console.log(`    backup ${dst} -> ${backup}`);
      fs.renameSync(dst, backup);
    }
  }

  try {
    const type = fs.statSync(src).isDirectory() ? 'dir' : 'file';  // matters on Windows
    fs.symlinkSync(src, dst, type);
    console.log(`    link ${dst} -> ${src}`);
  } catch (e) {
    if (process.platform === 'win32' && e.code === 'EPERM') {
      console.error(`!! symlink denied on Windows — enable Developer Mode or run as Administrator`);
    }
    throw e;
  }
}

console.log('==> Claude Code config bootstrap');
console.log(`    repo:   ${REPO}`);
console.log(`    target: ${CLAUDE}`);

console.log('==> Linking settings');
link(path.join(REPO, 'settings.json'),                        path.join(CLAUDE, 'settings.json'));
link(path.join(REPO, 'plugins', 'known_marketplaces.json'),   path.join(CLAUDE, 'plugins', 'known_marketplaces.json'));
// installed_plugins.json is machine-local cache (absolute paths, timestamps)
// and is regenerated by Claude Code — intentionally not synced.

const binSrc = path.join(REPO, 'bin');
if (fs.existsSync(binSrc)) {
  console.log('==> Linking bin');
  for (const name of fs.readdirSync(binSrc)) {
    const src = path.join(binSrc, name);
    const st = fs.statSync(src);
    if (!st.isFile()) continue;
    if (process.platform !== 'win32' && !(st.mode & 0o111)) continue;  // not executable
    link(src, path.join(LOCAL_BIN, name));
  }
  if (!process.env.PATH.split(path.delimiter).includes(LOCAL_BIN)) {
    console.log(`    note: add ${LOCAL_BIN} to PATH in your shell rc`);
  }
}

const skillsSrc = path.join(REPO, 'skills');
if (fs.existsSync(skillsSrc)) {
  console.log('==> Linking skills');
  for (const name of fs.readdirSync(skillsSrc)) {
    const src = path.join(skillsSrc, name);
    if (!fs.statSync(src).isDirectory()) continue;
    link(src, path.join(CLAUDE, 'skills', name));
  }
}

const rulesSrc = path.join(REPO, 'rules');
if (fs.existsSync(rulesSrc)) {
  console.log('==> Linking rules');
  fs.mkdirSync(path.join(CLAUDE, 'rules'), { recursive: true });
  for (const name of fs.readdirSync(rulesSrc)) {
    const src = path.join(rulesSrc, name);
    if (!fs.statSync(src).isFile()) continue;
    link(src, path.join(CLAUDE, 'rules', name));
  }
}

const skillsTxt = path.join(REPO, 'skills.txt');
if (fs.existsSync(skillsTxt)) {
  console.log('==> Checking third-party skills');
  const entries = fs.readFileSync(skillsTxt, 'utf8').split(/\r?\n/)
    .map(l => l.split('#')[0].trim()).filter(Boolean);

  // Derive the installed skill directory name from an entry line.
  // If --skill <name> is present, that's the installed name; otherwise use
  // the basename of the repo URL/shorthand (strip .git suffix).
  function skillName(entry) {
    const m = entry.match(/--skill\s+(\S+)/);
    if (m) return m[1];
    const src = entry.split(/\s+/)[0];
    return path.basename(src).replace(/\.git$/, '');
  }

  const missing = [];
  for (const s of entries) {
    const name = skillName(s);
    if (fs.existsSync(path.join(CLAUDE, 'skills', name)) || fs.existsSync(path.join(SKILLS_BASE, name))) {
      console.log(`    ok      ${name}`);
    } else {
      console.log(`    missing ${name}`);
      missing.push(s);
    }
  }
  if (missing.length) {
    for (const s of missing) {
      console.log(`==> Installing skill: ${s}`);
      const args = s.match(/(?:[^\s"']+|"[^"]*"|'[^']*')+/g) || [s];
      const r = spawnSync('npx', ['-y', 'skills', 'add', ...args], { stdio: 'inherit', shell: process.platform === 'win32' });
      if (r.status !== 0) console.log(`!! failed to install ${s}`);
    }
  }
}

console.log('==> Done');
console.log(`    Review machine-specific overrides in: ${path.join(CLAUDE, 'settings.local.json')}`);
